
version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "8080:8080"
  # redis:
  #   image: "redis:alpine"
  nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"